# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_browse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_browse.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_browse.setFont(font)
        self.btn_browse.setObjectName("btn_browse")
        self.textBrowser_browse = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_browse.setGeometry(QtCore.QRect(100, 10, 691, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.textBrowser_browse.setFont(font)
        self.textBrowser_browse.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_browse.setObjectName("textBrowser_browse")
        self.groupBox_filedetail = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_filedetail.setGeometry(QtCore.QRect(560, 50, 231, 441))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_filedetail.setFont(font)
        self.groupBox_filedetail.setObjectName("groupBox_filedetail")
        self.label_image_size = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_image_size.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.label_image_size.setTextFormat(QtCore.Qt.AutoText)
        self.label_image_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_image_size.setObjectName("label_image_size")
        self.label_date = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_date.setGeometry(QtCore.QRect(10, 110, 101, 21))
        self.label_date.setTextFormat(QtCore.Qt.AutoText)
        self.label_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date.setObjectName("label_date")
        self.label_frame = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_frame.setGeometry(QtCore.QRect(10, 190, 101, 21))
        self.label_frame.setTextFormat(QtCore.Qt.AutoText)
        self.label_frame.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_frame.setObjectName("label_frame")
        self.label_delta_x = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_delta_x.setGeometry(QtCore.QRect(10, 230, 101, 21))
        self.label_delta_x.setTextFormat(QtCore.Qt.AutoText)
        self.label_delta_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_delta_x.setObjectName("label_delta_x")
        self.label_delta_y = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_delta_y.setGeometry(QtCore.QRect(10, 270, 101, 21))
        self.label_delta_y.setTextFormat(QtCore.Qt.AutoText)
        self.label_delta_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_delta_y.setObjectName("label_delta_y")
        self.label_time = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_time.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.label_time.setTextFormat(QtCore.Qt.AutoText)
        self.label_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.label_image_size_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_image_size_show.setGeometry(QtCore.QRect(120, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_image_size_show.setFont(font)
        self.label_image_size_show.setStyleSheet("")
        self.label_image_size_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_image_size_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_size_show.setObjectName("label_image_size_show")
        self.label_date_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_date_show.setGeometry(QtCore.QRect(120, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_date_show.setFont(font)
        self.label_date_show.setStyleSheet("")
        self.label_date_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_date_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_show.setObjectName("label_date_show")
        self.label_time_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_time_show.setGeometry(QtCore.QRect(120, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_time_show.setFont(font)
        self.label_time_show.setStyleSheet("")
        self.label_time_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_time_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_show.setObjectName("label_time_show")
        self.label_frame_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_frame_show.setGeometry(QtCore.QRect(120, 190, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_frame_show.setFont(font)
        self.label_frame_show.setStyleSheet("")
        self.label_frame_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_frame_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frame_show.setObjectName("label_frame_show")
        self.label_filetype_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_filetype_show.setGeometry(QtCore.QRect(120, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_filetype_show.setFont(font)
        self.label_filetype_show.setStyleSheet("")
        self.label_filetype_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_filetype_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_filetype_show.setObjectName("label_filetype_show")
        self.label_filetype = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_filetype.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label_filetype.setTextFormat(QtCore.Qt.AutoText)
        self.label_filetype.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filetype.setObjectName("label_filetype")
        self.label_mm1 = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_mm1.setGeometry(QtCore.QRect(190, 230, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_mm1.setFont(font)
        self.label_mm1.setTextFormat(QtCore.Qt.AutoText)
        self.label_mm1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_mm1.setObjectName("label_mm1")
        self.label_mm2 = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_mm2.setGeometry(QtCore.QRect(190, 270, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_mm2.setFont(font)
        self.label_mm2.setTextFormat(QtCore.Qt.AutoText)
        self.label_mm2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_mm2.setObjectName("label_mm2")
        self.label_search_window = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_search_window.setGeometry(QtCore.QRect(0, 350, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_search_window.setFont(font)
        self.label_search_window.setTextFormat(QtCore.Qt.AutoText)
        self.label_search_window.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_search_window.setObjectName("label_search_window")
        self.label_template_block = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_template_block.setGeometry(QtCore.QRect(10, 310, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_template_block.setFont(font)
        self.label_template_block.setTextFormat(QtCore.Qt.AutoText)
        self.label_template_block.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_template_block.setObjectName("label_template_block")
        self.label_pixel1 = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_pixel1.setGeometry(QtCore.QRect(190, 310, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_pixel1.setFont(font)
        self.label_pixel1.setTextFormat(QtCore.Qt.AutoText)
        self.label_pixel1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pixel1.setObjectName("label_pixel1")
        self.label_pixel2 = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_pixel2.setGeometry(QtCore.QRect(190, 350, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_pixel2.setFont(font)
        self.label_pixel2.setTextFormat(QtCore.Qt.AutoText)
        self.label_pixel2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pixel2.setObjectName("label_pixel2")
        self.spinBox_temp_size = QtWidgets.QSpinBox(self.groupBox_filedetail)
        self.spinBox_temp_size.setGeometry(QtCore.QRect(120, 310, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.spinBox_temp_size.setFont(font)
        self.spinBox_temp_size.setObjectName("spinBox_temp_size")
        self.spinBox_search_range = QtWidgets.QSpinBox(self.groupBox_filedetail)
        self.spinBox_search_range.setGeometry(QtCore.QRect(120, 350, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.spinBox_search_range.setFont(font)
        self.spinBox_search_range.setObjectName("spinBox_search_range")
        self.doubleSpinBox_delta_x = QtWidgets.QDoubleSpinBox(self.groupBox_filedetail)
        self.doubleSpinBox_delta_x.setGeometry(QtCore.QRect(120, 230, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.doubleSpinBox_delta_x.setFont(font)
        self.doubleSpinBox_delta_x.setDecimals(3)
        self.doubleSpinBox_delta_x.setSingleStep(0.05)
        self.doubleSpinBox_delta_x.setObjectName("doubleSpinBox_delta_x")
        self.doubleSpinBox_delta_y = QtWidgets.QDoubleSpinBox(self.groupBox_filedetail)
        self.doubleSpinBox_delta_y.setGeometry(QtCore.QRect(120, 270, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.doubleSpinBox_delta_y.setFont(font)
        self.doubleSpinBox_delta_y.setDecimals(3)
        self.doubleSpinBox_delta_y.setSingleStep(0.05)
        self.doubleSpinBox_delta_y.setObjectName("doubleSpinBox_delta_y")
        self.label_image_size.raise_()
        self.label_date.raise_()
        self.label_frame.raise_()
        self.label_delta_x.raise_()
        self.label_delta_y.raise_()
        self.label_time.raise_()
        self.label_image_size_show.raise_()
        self.label_date_show.raise_()
        self.label_time_show.raise_()
        self.label_frame_show.raise_()
        self.label_filetype_show.raise_()
        self.label_filetype.raise_()
        self.label_mm1.raise_()
        self.label_mm2.raise_()
        self.label_template_block.raise_()
        self.label_search_window.raise_()
        self.label_pixel1.raise_()
        self.label_pixel2.raise_()
        self.spinBox_temp_size.raise_()
        self.spinBox_search_range.raise_()
        self.doubleSpinBox_delta_x.raise_()
        self.doubleSpinBox_delta_y.raise_()
        self.groupBox_show_curve = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_show_curve.setGeometry(QtCore.QRect(10, 500, 481, 311))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_show_curve.setFont(font)
        self.groupBox_show_curve.setObjectName("groupBox_show_curve")
        self.label_show_curve = QtWidgets.QLabel(self.groupBox_show_curve)
        self.label_show_curve.setGeometry(QtCore.QRect(10, 20, 461, 281))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_show_curve.setFont(font)
        self.label_show_curve.setStyleSheet("background-color: rgba(220, 220, 220, 200);")
        self.label_show_curve.setText("")
        self.label_show_curve.setAlignment(QtCore.Qt.AlignCenter)
        self.label_show_curve.setObjectName("label_show_curve")
        self.groupBox_preview = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_preview.setGeometry(QtCore.QRect(10, 50, 531, 441))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_preview.setFont(font)
        self.groupBox_preview.setObjectName("groupBox_preview")
        self.label_preview = QtWidgets.QLabel(self.groupBox_preview)
        self.label_preview.setGeometry(QtCore.QRect(10, 30, 511, 361))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_preview.setFont(font)
        self.label_preview.setStyleSheet("background-color: rgba(220, 220, 220, 200);")
        self.label_preview.setText("")
        self.label_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_preview.setObjectName("label_preview")
        self.label_manufacturer = QtWidgets.QLabel(self.groupBox_preview)
        self.label_manufacturer.setGeometry(QtCore.QRect(20, 360, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_manufacturer.setFont(font)
        self.label_manufacturer.setObjectName("label_manufacturer")
        self.horizontalSlider_preview = QtWidgets.QSlider(self.groupBox_preview)
        self.horizontalSlider_preview.setGeometry(QtCore.QRect(10, 405, 401, 21))
        self.horizontalSlider_preview.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_preview.setObjectName("horizontalSlider_preview")
        self.btn_color = QtWidgets.QPushButton(self.groupBox_preview)
        self.btn_color.setGeometry(QtCore.QRect(430, 400, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_color.setFont(font)
        self.btn_color.setAutoRepeatDelay(-1)
        self.btn_color.setAutoRepeatInterval(-1)
        self.btn_color.setObjectName("btn_color")
        self.label_preview.raise_()
        self.horizontalSlider_preview.raise_()
        self.label_manufacturer.raise_()
        self.btn_color.raise_()
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(500, 500, 291, 231))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn_run = QtWidgets.QPushButton(self.groupBox)
        self.btn_run.setGeometry(QtCore.QRect(190, 190, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_run.setFont(font)
        self.btn_run.setAutoRepeatDelay(-1)
        self.btn_run.setAutoRepeatInterval(-1)
        self.btn_run.setObjectName("btn_run")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 271, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_model = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_model.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_model.setObjectName("label_model")
        self.horizontalLayout.addWidget(self.label_model)
        self.radioButton_line = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_line.setFont(font)
        self.radioButton_line.setChecked(True)
        self.radioButton_line.setObjectName("radioButton_line")
        self.horizontalLayout.addWidget(self.radioButton_line)
        self.radioButton_draw = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_draw.setFont(font)
        self.radioButton_draw.setObjectName("radioButton_draw")
        self.horizontalLayout.addWidget(self.radioButton_draw)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 271, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_cost = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_cost.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_cost.setObjectName("horizontalLayout_cost")
        self.label_model_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_model_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_model_3.setObjectName("label_model_3")
        self.horizontalLayout_cost.addWidget(self.label_model_3)
        self.radioButton_SAD = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_SAD.setFont(font)
        self.radioButton_SAD.setChecked(True)
        self.radioButton_SAD.setObjectName("radioButton_SAD")
        self.horizontalLayout_cost.addWidget(self.radioButton_SAD)
        self.radioButton_SSD = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_SSD.setFont(font)
        self.radioButton_SSD.setObjectName("radioButton_SSD")
        self.horizontalLayout_cost.addWidget(self.radioButton_SSD)
        self.checkBox_show_process = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_show_process.setGeometry(QtCore.QRect(20, 190, 121, 31))
        self.checkBox_show_process.setObjectName("checkBox_show_process")
        self.label_NULL = QtWidgets.QLabel(self.groupBox)
        self.label_NULL.setGeometry(QtCore.QRect(10, 60, 74, 29))
        self.label_NULL.setText("")
        self.label_NULL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_NULL.setObjectName("label_NULL")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 90, 271, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget_mode = QtWidgets.QStackedWidget(self.groupBox)
        self.stackedWidget_mode.setGeometry(QtCore.QRect(10, 100, 271, 91))
        self.stackedWidget_mode.setObjectName("stackedWidget_mode")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 10, 271, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_curve = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_curve.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_curve.setObjectName("horizontalLayout_curve")
        self.label_curve = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_curve.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_curve.setObjectName("label_curve")
        self.horizontalLayout_curve.addWidget(self.label_curve)
        self.radioButton_strain = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_strain.setChecked(True)
        self.radioButton_strain.setObjectName("radioButton_strain")
        self.horizontalLayout_curve.addWidget(self.radioButton_strain)
        self.radioButton_distance = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_distance.setObjectName("radioButton_distance")
        self.horizontalLayout_curve.addWidget(self.radioButton_distance)
        self.label_curve.raise_()
        self.radioButton_strain.raise_()
        self.radioButton_distance.raise_()
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.page)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 40, 271, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_optimize = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_optimize.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_optimize.setObjectName("horizontalLayout_optimize")
        self.label_optimize = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_optimize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_optimize.setObjectName("label_optimize")
        self.horizontalLayout_optimize.addWidget(self.label_optimize)
        self.radioButton_spline = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButton_spline.setChecked(True)
        self.radioButton_spline.setObjectName("radioButton_spline")
        self.horizontalLayout_optimize.addWidget(self.radioButton_spline)
        self.radioButton_original = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButton_original.setObjectName("radioButton_original")
        self.horizontalLayout_optimize.addWidget(self.radioButton_original)
        self.stackedWidget_mode.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 271, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_DRAWING_DELAY = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_DRAWING_DELAY.setFont(font)
        self.label_DRAWING_DELAY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_DRAWING_DELAY.setObjectName("label_DRAWING_DELAY")
        self.horizontalLayout_4.addWidget(self.label_DRAWING_DELAY)
        self.spinBox_drawing_delay = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.spinBox_drawing_delay.setObjectName("spinBox_drawing_delay")
        self.horizontalLayout_4.addWidget(self.spinBox_drawing_delay)
        self.spinBox_drawing_delay.raise_()
        self.label_DRAWING_DELAY.raise_()
        self.label.raise_()
        self.stackedWidget_mode.addWidget(self.page_2)
        self.groupBox_save = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_save.setGeometry(QtCore.QRect(500, 740, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_save.setFont(font)
        self.groupBox_save.setObjectName("groupBox_save")
        self.btn_save_result = QtWidgets.QPushButton(self.groupBox_save)
        self.btn_save_result.setGeometry(QtCore.QRect(10, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_save_result.setFont(font)
        self.btn_save_result.setObjectName("btn_save_result")
        self.btn_save_csv = QtWidgets.QPushButton(self.groupBox_save)
        self.btn_save_csv.setGeometry(QtCore.QRect(120, 30, 101, 31))
        self.btn_save_csv.setObjectName("btn_save_csv")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_mode.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_browse.setText(_translate("MainWindow", "Browse"))
        self.groupBox_filedetail.setTitle(_translate("MainWindow", "File Detail"))
        self.label_image_size.setText(_translate("MainWindow", "Image size :"))
        self.label_date.setText(_translate("MainWindow", "Date :"))
        self.label_frame.setText(_translate("MainWindow", "Frame :"))
        self.label_delta_x.setText(_translate("MainWindow", "Delta X :"))
        self.label_delta_y.setText(_translate("MainWindow", "Delta Y :"))
        self.label_time.setText(_translate("MainWindow", "Time :"))
        self.label_image_size_show.setText(_translate("MainWindow", "___________"))
        self.label_date_show.setText(_translate("MainWindow", "___________"))
        self.label_time_show.setText(_translate("MainWindow", "___________"))
        self.label_frame_show.setText(_translate("MainWindow", "___________"))
        self.label_filetype_show.setText(_translate("MainWindow", "___________"))
        self.label_filetype.setText(_translate("MainWindow", "File type :"))
        self.label_mm1.setText(_translate("MainWindow", "mm"))
        self.label_mm2.setText(_translate("MainWindow", "mm"))
        self.label_search_window.setText(_translate("MainWindow", "Search Window :"))
        self.label_template_block.setText(_translate("MainWindow", "Template Block :"))
        self.label_pixel1.setText(_translate("MainWindow", "pixels"))
        self.label_pixel2.setText(_translate("MainWindow", "pixels"))
        self.groupBox_show_curve.setTitle(_translate("MainWindow", "Curve"))
        self.groupBox_preview.setTitle(_translate("MainWindow", "Preview"))
        self.label_manufacturer.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_color.setText(_translate("MainWindow", "Color"))
        self.groupBox.setTitle(_translate("MainWindow", "Cv2 Console"))
        self.btn_run.setText(_translate("MainWindow", "Run"))
        self.label_model.setText(_translate("MainWindow", "Mode  |"))
        self.radioButton_line.setText(_translate("MainWindow", "line"))
        self.radioButton_draw.setText(_translate("MainWindow", "draw"))
        self.label_model_3.setText(_translate("MainWindow", "Cost  |"))
        self.radioButton_SAD.setText(_translate("MainWindow", "SAD"))
        self.radioButton_SSD.setText(_translate("MainWindow", "SSD"))
        self.checkBox_show_process.setText(_translate("MainWindow", "Show process"))
        self.label_curve.setText(_translate("MainWindow", "Curve |"))
        self.radioButton_strain.setText(_translate("MainWindow", "Strain"))
        self.radioButton_distance.setText(_translate("MainWindow", "Distance"))
        self.label_optimize.setText(_translate("MainWindow", "Optimize |"))
        self.radioButton_spline.setText(_translate("MainWindow", "Spline"))
        self.radioButton_original.setText(_translate("MainWindow", "Original"))
        self.label_DRAWING_DELAY.setText(_translate("MainWindow", "drawing delay | "))
        self.groupBox_save.setTitle(_translate("MainWindow", "Save"))
        self.btn_save_result.setText(_translate("MainWindow", "Save Result"))
        self.btn_save_csv.setText(_translate("MainWindow", "Save CSV"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
