# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 758)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_browse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_browse.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_browse.setFont(font)
        self.btn_browse.setObjectName("btn_browse")
        self.textBrowser_browse = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_browse.setGeometry(QtCore.QRect(100, 10, 691, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.textBrowser_browse.setFont(font)
        self.textBrowser_browse.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_browse.setObjectName("textBrowser_browse")
        self.groupBox_filedetail = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_filedetail.setGeometry(QtCore.QRect(560, 50, 231, 391))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_filedetail.setFont(font)
        self.groupBox_filedetail.setObjectName("groupBox_filedetail")
        self.label_image_size = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_image_size.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.label_image_size.setTextFormat(QtCore.Qt.AutoText)
        self.label_image_size.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_image_size.setObjectName("label_image_size")
        self.label_date = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_date.setGeometry(QtCore.QRect(10, 110, 101, 21))
        self.label_date.setTextFormat(QtCore.Qt.AutoText)
        self.label_date.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_date.setObjectName("label_date")
        self.label_frame = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_frame.setGeometry(QtCore.QRect(10, 190, 101, 21))
        self.label_frame.setTextFormat(QtCore.Qt.AutoText)
        self.label_frame.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_frame.setObjectName("label_frame")
        self.label_delta_x = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_delta_x.setGeometry(QtCore.QRect(10, 230, 101, 21))
        self.label_delta_x.setTextFormat(QtCore.Qt.AutoText)
        self.label_delta_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_delta_x.setObjectName("label_delta_x")
        self.label_delta_y = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_delta_y.setGeometry(QtCore.QRect(10, 270, 101, 21))
        self.label_delta_y.setTextFormat(QtCore.Qt.AutoText)
        self.label_delta_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_delta_y.setObjectName("label_delta_y")
        self.label_time = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_time.setGeometry(QtCore.QRect(10, 150, 101, 21))
        self.label_time.setTextFormat(QtCore.Qt.AutoText)
        self.label_time.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.label_image_size_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_image_size_show.setGeometry(QtCore.QRect(120, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_image_size_show.setFont(font)
        self.label_image_size_show.setStyleSheet("")
        self.label_image_size_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_image_size_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image_size_show.setObjectName("label_image_size_show")
        self.label_date_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_date_show.setGeometry(QtCore.QRect(120, 110, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_date_show.setFont(font)
        self.label_date_show.setStyleSheet("")
        self.label_date_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_date_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date_show.setObjectName("label_date_show")
        self.label_time_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_time_show.setGeometry(QtCore.QRect(120, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_time_show.setFont(font)
        self.label_time_show.setStyleSheet("")
        self.label_time_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_time_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_show.setObjectName("label_time_show")
        self.label_frame_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_frame_show.setGeometry(QtCore.QRect(120, 190, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_frame_show.setFont(font)
        self.label_frame_show.setStyleSheet("")
        self.label_frame_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_frame_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frame_show.setObjectName("label_frame_show")
        self.label_filetype_show = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_filetype_show.setGeometry(QtCore.QRect(120, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setUnderline(False)
        self.label_filetype_show.setFont(font)
        self.label_filetype_show.setStyleSheet("")
        self.label_filetype_show.setTextFormat(QtCore.Qt.AutoText)
        self.label_filetype_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_filetype_show.setObjectName("label_filetype_show")
        self.label_filetype = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_filetype.setGeometry(QtCore.QRect(10, 30, 101, 21))
        self.label_filetype.setTextFormat(QtCore.Qt.AutoText)
        self.label_filetype.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_filetype.setObjectName("label_filetype")
        self.label_mm1 = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_mm1.setGeometry(QtCore.QRect(190, 230, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_mm1.setFont(font)
        self.label_mm1.setTextFormat(QtCore.Qt.AutoText)
        self.label_mm1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_mm1.setObjectName("label_mm1")
        self.label_mm2 = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_mm2.setGeometry(QtCore.QRect(190, 270, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_mm2.setFont(font)
        self.label_mm2.setTextFormat(QtCore.Qt.AutoText)
        self.label_mm2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_mm2.setObjectName("label_mm2")
        self.label_search_window = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_search_window.setGeometry(QtCore.QRect(0, 350, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_search_window.setFont(font)
        self.label_search_window.setTextFormat(QtCore.Qt.AutoText)
        self.label_search_window.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_search_window.setObjectName("label_search_window")
        self.label_template_block = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_template_block.setGeometry(QtCore.QRect(10, 310, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_template_block.setFont(font)
        self.label_template_block.setTextFormat(QtCore.Qt.AutoText)
        self.label_template_block.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_template_block.setObjectName("label_template_block")
        self.label_pixel1 = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_pixel1.setGeometry(QtCore.QRect(190, 310, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_pixel1.setFont(font)
        self.label_pixel1.setTextFormat(QtCore.Qt.AutoText)
        self.label_pixel1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pixel1.setObjectName("label_pixel1")
        self.label_pixel2 = QtWidgets.QLabel(self.groupBox_filedetail)
        self.label_pixel2.setGeometry(QtCore.QRect(190, 350, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_pixel2.setFont(font)
        self.label_pixel2.setTextFormat(QtCore.Qt.AutoText)
        self.label_pixel2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_pixel2.setObjectName("label_pixel2")
        self.spinBox_temp_size = QtWidgets.QSpinBox(self.groupBox_filedetail)
        self.spinBox_temp_size.setGeometry(QtCore.QRect(120, 310, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.spinBox_temp_size.setFont(font)
        self.spinBox_temp_size.setObjectName("spinBox_temp_size")
        self.spinBox_search_range = QtWidgets.QSpinBox(self.groupBox_filedetail)
        self.spinBox_search_range.setGeometry(QtCore.QRect(120, 350, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.spinBox_search_range.setFont(font)
        self.spinBox_search_range.setObjectName("spinBox_search_range")
        self.doubleSpinBox_delta_x = QtWidgets.QDoubleSpinBox(self.groupBox_filedetail)
        self.doubleSpinBox_delta_x.setGeometry(QtCore.QRect(120, 230, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.doubleSpinBox_delta_x.setFont(font)
        self.doubleSpinBox_delta_x.setDecimals(3)
        self.doubleSpinBox_delta_x.setSingleStep(0.05)
        self.doubleSpinBox_delta_x.setObjectName("doubleSpinBox_delta_x")
        self.doubleSpinBox_delta_y = QtWidgets.QDoubleSpinBox(self.groupBox_filedetail)
        self.doubleSpinBox_delta_y.setGeometry(QtCore.QRect(120, 270, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.doubleSpinBox_delta_y.setFont(font)
        self.doubleSpinBox_delta_y.setDecimals(3)
        self.doubleSpinBox_delta_y.setSingleStep(0.05)
        self.doubleSpinBox_delta_y.setObjectName("doubleSpinBox_delta_y")
        self.label_image_size.raise_()
        self.label_date.raise_()
        self.label_frame.raise_()
        self.label_delta_x.raise_()
        self.label_delta_y.raise_()
        self.label_time.raise_()
        self.label_image_size_show.raise_()
        self.label_date_show.raise_()
        self.label_time_show.raise_()
        self.label_frame_show.raise_()
        self.label_filetype_show.raise_()
        self.label_filetype.raise_()
        self.label_mm1.raise_()
        self.label_mm2.raise_()
        self.label_template_block.raise_()
        self.label_search_window.raise_()
        self.label_pixel1.raise_()
        self.label_pixel2.raise_()
        self.spinBox_temp_size.raise_()
        self.spinBox_search_range.raise_()
        self.doubleSpinBox_delta_x.raise_()
        self.doubleSpinBox_delta_y.raise_()
        self.groupBox_curve = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_curve.setGeometry(QtCore.QRect(10, 500, 531, 211))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_curve.setFont(font)
        self.groupBox_curve.setObjectName("groupBox_curve")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(560, 680, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.groupBox_preview = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_preview.setGeometry(QtCore.QRect(10, 50, 531, 441))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_preview.setFont(font)
        self.groupBox_preview.setObjectName("groupBox_preview")
        self.label_preview = QtWidgets.QLabel(self.groupBox_preview)
        self.label_preview.setGeometry(QtCore.QRect(10, 30, 511, 361))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_preview.setFont(font)
        self.label_preview.setStyleSheet("background-color: rgba(220, 220, 220, 200);")
        self.label_preview.setText("")
        self.label_preview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_preview.setObjectName("label_preview")
        self.btn_run = QtWidgets.QPushButton(self.groupBox_preview)
        self.btn_run.setGeometry(QtCore.QRect(450, 400, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_run.setFont(font)
        self.btn_run.setAutoRepeatDelay(-1)
        self.btn_run.setAutoRepeatInterval(-1)
        self.btn_run.setObjectName("btn_run")
        self.label_manufacturer = QtWidgets.QLabel(self.groupBox_preview)
        self.label_manufacturer.setGeometry(QtCore.QRect(20, 360, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.label_manufacturer.setFont(font)
        self.label_manufacturer.setObjectName("label_manufacturer")
        self.horizontalSlider_preview = QtWidgets.QSlider(self.groupBox_preview)
        self.horizontalSlider_preview.setGeometry(QtCore.QRect(10, 405, 351, 21))
        self.horizontalSlider_preview.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_preview.setObjectName("horizontalSlider_preview")
        self.btn_color = QtWidgets.QPushButton(self.groupBox_preview)
        self.btn_color.setGeometry(QtCore.QRect(370, 400, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.btn_color.setFont(font)
        self.btn_color.setAutoRepeatDelay(-1)
        self.btn_color.setAutoRepeatInterval(-1)
        self.btn_color.setObjectName("btn_color")
        self.label_preview.raise_()
        self.btn_run.raise_()
        self.horizontalSlider_preview.raise_()
        self.label_manufacturer.raise_()
        self.btn_color.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_browse.setText(_translate("MainWindow", "Browse"))
        self.groupBox_filedetail.setTitle(_translate("MainWindow", "File Detail"))
        self.label_image_size.setText(_translate("MainWindow", "Image size :"))
        self.label_date.setText(_translate("MainWindow", "Date :"))
        self.label_frame.setText(_translate("MainWindow", "Frame :"))
        self.label_delta_x.setText(_translate("MainWindow", "Delta X :"))
        self.label_delta_y.setText(_translate("MainWindow", "Delta Y :"))
        self.label_time.setText(_translate("MainWindow", "Time :"))
        self.label_image_size_show.setText(_translate("MainWindow", "___________"))
        self.label_date_show.setText(_translate("MainWindow", "___________"))
        self.label_time_show.setText(_translate("MainWindow", "___________"))
        self.label_frame_show.setText(_translate("MainWindow", "___________"))
        self.label_filetype_show.setText(_translate("MainWindow", "___________"))
        self.label_filetype.setText(_translate("MainWindow", "File type :"))
        self.label_mm1.setText(_translate("MainWindow", "mm"))
        self.label_mm2.setText(_translate("MainWindow", "mm"))
        self.label_search_window.setText(_translate("MainWindow", "Search Window :"))
        self.label_template_block.setText(_translate("MainWindow", "Template Block :"))
        self.label_pixel1.setText(_translate("MainWindow", "pixels"))
        self.label_pixel2.setText(_translate("MainWindow", "pixels"))
        self.groupBox_curve.setTitle(_translate("MainWindow", "Curve"))
        self.btn_save.setText(_translate("MainWindow", "Save Result"))
        self.groupBox_preview.setTitle(_translate("MainWindow", "Preview"))
        self.btn_run.setText(_translate("MainWindow", "Run"))
        self.label_manufacturer.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btn_color.setText(_translate("MainWindow", "Color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
